from fastapi import APIRouter, HTTPException, Depends, status, Body

from src.database.databaseNeo4j import neo4j_driver

from src.models.provenance.activityModel import ActivityModel
from src.models.provenance.entityModel import EntityModel
from src.models.hybrid.activityEntityModel import ActivityEntityModel

router = APIRouter(
   prefix = "/was-generated-by",
   tags = ["Was Generated By Relationship"],
   responses = {404: {"description": "Not Found"}},
)

@router.post('/post', response_description="Create Was Used")
async def create_was_used(data: ActivityEntityModel = Body(...)):
   activity = dict(data.activity)
   entity = dict(data.entity)
   
   query = (
      "MERGE (activity:Activity { name: $activity.name, provType: $activity.provType, start_time: $activity.start_time, end_time: $activity.end_time }) "
      "MERGE (entity:Entity { name: $entity.name, provType: $entity.provType }) "
      "CREATE (entity)-[:WASGENERATEDBY]->(activity) "
      "RETURN activity, entity"
   )
   
   with neo4j_driver.session() as session:      
      result = session.run(query, activity=activity, entity=entity)
      resultData = result.data()[0]
      activityData = resultData['activity']
      entityData = resultData['entity']
   
   response = {
      'activity': activityData,
      'entity': entityData
   }
   return response

# @router.put('/update', response_description="Update Was Used")
# def update_was_used(data: ActivityEntityModel = Body(...)):
#    activity = dict(data.activity)
#    entity = dict(data.entity)
   
#    searchRelationship = (
#       "MATCH (activity:Activity) WHERE activity.name = $activity.name "
#       "MATCH (entity:Entity) WHERE entity.name = $entity.name "
#       "MATCH (entity)-[rel:WAS_GENERATED_BY]->(activity) "
#       "RETURN rel"
#    )
   
#    query = (
#       "MATCH (activity:Activity) WHERE activity.name = $activity.name "
#       "MATCH (entity:Entity) WHERE entity.name = $entity.name "
#       "MATCH (entity)-[rel:WAS_GENERATED_BY]->(activity) "
#       "SET activity.end_time = $activity.end_time "
#       "RETURN rel, activity, entity"
#    )
   
#    with neo4j_driver.session() as session:
#       checkRelationship = session.run(query=searchRelationship, activity=activity, entity=entity)
#       if checkRelationship.data():
#          result = session.run(query, activity=activity, entity=entity)
#          resultData = result.data()[0]
   
#    return resultData